### ISSUE TITLE
*.groupBy'

### ISSUE THREAD

**Issue by cmorley191** [ntwilson/SafetyFirst#44]
(* = List/Array/Seq, here I just say Seq)

Seq.groupBy returns distinct subsequences of the original sequence that are _not empty_ -- this is an expected (though I will admit, [undocumented](https://msdn.microsoft.com/visualfsharpdocs/conceptual/seq.groupby%5b%27t%2c%27key%5d-function-%5bfsharp%5d)) behavior of the native fsharp Seq.groupBy

Therefore, this library should extend the native fsharp Seq.groupBy with its own implementation that returns NonEmpty subsequences:

```
let groupBy' grouper lst = 
  lst 
  |> Seq.groupBy grouper 
  |> Seq.map (fun (key, group) -> (key, group |> Seq.NonEmpty.ofSeq' |> Result.unless "groupBy is not supposed to produce an empty group"))
```

`groupBy'` clearly does not appear to be a safe implementation (there is an `unless` and it does not return a Result). However, if we trust the native fsharp groupBy implementation to never produce empty groups, this function should be safe.

**Comment by ntwilson** [comment]
Yeah, there's a lot of code in SafetyFirst that isn't provably safe, but makes some assumptions that supposedly are valid based on FSharp.Core.
I like this idea, though I do want to come up with some alternative name for this though.  It says in the docs that the trailing `'` is intended to signify that the operation can fail, and returns a `Result<_,_>`, but this modified `groupBy` doesn't fail.  One alternative is to call it `groupBy`, but drop it in the NonEmpty modules for each collection.  It might be a little misleading though since you might expect the signature `('a -> 'b) -> NonEmptySeq<'a> -> NonEmptySeq<('b * NonEmptySeq<'a>)>`, which would also be totally valid.  Another alternative is to just use the signature I just posted, and require the caller to do:
```
match xs with
| Empty -> Seq.empty
| NotEmpty ys -> seq (Seq.NonEmpty.groupBy grouper ys)
```
if their input list can be empty.  Another alternative is to come up with some alternate name for this function.  Like `group`?  `groupWith`?  (I'd like to stick with having "group" in the name so that intellisense would show it next to the groupBy function).
