### ISSUE TITLE
Make concrete C# enumerable types extend FSeq where appropriate

### ISSUE THREAD

**Issue by cmorley191** [ntwilson/SafetyFirst#51]
I don't even know if this is possible, so maybe this is more of a discussion issue that may spawn other issues, or maybe not.

System.Collections.Generic has lots of concrete (is that the correct term?) collection types: Dictionary, HashSet, List, LinkedList, Queue, Stack are the ones I recognize immediately.

Dictionary, List, and HashSet are certainly finite, so it'd be nice if they already were of type FSeq. I don't know if there's a way to create an infinite LinkedList, Queue, or Stack.

Is there any way we can just override that namespace and say "oh yeah, these classes are FSeq's"

It'd also be nice for their properties to return FSeq's (e.g., Dictionary.Values is a ValueCollection -- ValueCollection should be an FSeq)

**Comment by ntwilson** [comment]
Closing this one too, because again it's not possible.
Que me standing on a soap box yelling at how OO is a broken paradigm and we should all be using typeclasses.  The problem with OO is you have to know all of the capabilities of an object at the time you define the object.  That or you monkey patch, but that's not even really compatible with a static type system.
